/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.labs.prova;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.net.ServerSocket;
import java.net.Socket;

import org.junit.jupiter.api.Test;

class ApplicationTest {
    
    @Test 
    void get_port() throws Exception {
        Application application = new Application();
        int port = application.getPort(new String[]{"8933"});
        assertEquals(8933, port);
    }
    
    @Test
    void inject_handler() throws Exception {
        ServerSocket serverSocket = mock(ServerSocket.class);
        Socket socket = mock(Socket.class);
        when(serverSocket.getLocalPort()).thenReturn(8933);
        when(serverSocket.accept()).thenReturn(socket);
        when(socket.getOutputStream()).thenReturn(System.out);
        when(socket.getInputStream()).thenReturn(System.in);
        Application application = new Application();
        application.injectHandler(serverSocket);
    }
}
